services:
  iresults-test:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: iresults-bot:test
    env_file: .env.example
    volumes:
      - ./data:/app/data
      - ./tests:/app/tests
    command: python -m pytest tests/ -v