services:
  python:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - IRACING_USERNAME=${IRACING_USERNAME}
      - IRACING_PASSWORD=${IRACING_PASSWORD}
    command: "python -m src.discord_bot"