services:
  python:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - IRACING_USERNAME=${IRACING_USERNAME}
      - IRACING_PASSWORD=${IRACING_PASSWORD}
    command: "python -m src.last_race_details"